on:
  release:
    types: [ published ]

name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Fetch release archives
        uses: actions/download-artifact@v4
      - name: Mark binary as executable
        run: |
          chmod +x ff_config-linux-x64/ff_config
          chmod +x ff_config-linux-arm64/ff_config
      - name: Create release zip
        run:
          for i in ff_config-*/; do zip -r -j "${i%/}.zip" "$i"; done
      - name: Get the tag name
        id: tag
        run: echo TAG=${{ github.event.release.tag_name }} >> $GITHUB_OUTPUT
      - name: Upload release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.tag.outputs.TAG }} ff_config-*.zip
